on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
name: Create Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'extension_filename.ext'
        exclusions: '*.git* /*node_modules/* .editorconfig body.md *.psd'
    - name: Upload Asset
      uses: PeerXu/upload-asset@v1
      with:
        file: 'extension_filename.ext'
        with_sha1: true
        suffix: .ext
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
